name: 📦 • Install and Test
on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-24.04
permissions:
  contents: read
jobs:
  install:
    name: 📦 ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      - name: Enable long paths on Windows and Git
        if: runner.os == 'Windows'
        run: |
          reg add HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f
          git config --system core.longpaths true
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@a4d08616f5b614053bce228ddf881592f69d61d4 # v1.5.9
        with:
          prepend_symlinks_to_path: false
          override_cache_key: cpp-install-tests-${{ inputs.runs-on }}
          windows_compile_environment: msvc
      - name: Setup mold
        if: runner.os == 'Linux'
        uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1
      - name: Build, install, relocate, and test
        run: cmake -P test/install.cmake
