name: 🇨 • Tests • ubuntu
on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-24.04
      config:
        type: string
        default: Release
permissions:
  contents: read
jobs:
  cpp-tests-ubuntu:
    name: 🐧 ${{ inputs.runs-on }} ${{ inputs.config }}
    runs-on: ${{ inputs.runs-on }}
    env:
      CONFIG: ${{ inputs.config }}
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: Chocobo1/setup-ccache-action@a4d08616f5b614053bce228ddf881592f69d61d4 # v1.5.9
        with:
          prepend_symlinks_to_path: false
          override_cache_key: cpp-${{ inputs.runs-on }}-${{ inputs.config }}
      - name: Setup mold
        uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1
      - name: Configure
        shell: bash
        run: cmake -S . -B build/native -DCMAKE_BUILD_TYPE="$CONFIG"
      - name: Build
        shell: bash
        run: cmake --build build/native --config "$CONFIG"
      - name: Test
        shell: bash
        run: ctest --test-dir build/native -C "$CONFIG" --output-on-failure --timeout 600
